### ISSUE TITLE
ArgumentOutOfRangeException for no results

### ISSUE THREAD

**Issue by kevbite** [Narochno/Narochno.Credstash#15]
When a key doesn't exist in the store `GetSecretAsync` throws an  `ArgumentOutOfRangeException` instead of returning `Optional<T>` with `HasValue` set to `false`

Exception Details:

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CredstashTester.Program.Main(String[] args) in C:\dev\Narochno\Narochno.Credstash\misc\CredstashTester\Program.cs:line 20

Inner Exception 1:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

**Comment by kevbite** [comment]
Nice one!
